services:
  db:
    container_name: wanted_db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jpa
    ports:
      - "35432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
